### ISSUE TITLE
Some bad cases about FaceID & CLIP Guidance Human Face Generation

### ISSUE THREAD

**Issue by boom9807** [KellyYutongHe/mpgd_pytorch#1]
Thanks for your contribution. There are some issues I met when running codes in ./nonlinear/Face-GD.
Generation Results：

1. face-clip
a) ae  
prompt: a headshot of a person wearing **green** lipstick
(ddim50_eta1.0_rho1.0_seed0_repeat1_500-200)
![a headshot of a person wearing green lipstick_0000](https://github.com/KellyYutongHe/mpgd_pytorch/assets/42735246/a8abaf69-4571-4f18-887b-79eb43464e3a) 
![a headshot of a person wearing green lipstick_0001](https://github.com/KellyYutongHe/mpgd_pytorch/assets/42735246/3ab5db92-26cc-4fb6-8165-543126f7882e)
b) z  
prompt: a headshot of a person wearing **blue** lipstick
(ddim50_eta1.0_rho2.0_seed0_repeat1_500-200)
![a headshot of a person wearing blue lipstick_0000](https://github.com/KellyYutongHe/mpgd_pytorch/assets/42735246/ffa8d81f-2c56-4161-a2b9-08dad16c00c3)
prompt: a headshot of a tough guy with purple hair   
(ddim50_eta1.0_rho2.5_seed0_repeat3_700-400)
![a headshot of a tough guy with purple hair_0000](https://github.com/KellyYutongHe/mpgd_pytorch/assets/42735246/ceb39f5f-f191-4892-a9c5-fb89e87af303)
![a headshot of a tough guy with purple hair_0001](https://github.com/KellyYutongHe/mpgd_pytorch/assets/42735246/439aca75-1b68-480b-a210-c2dea2c5c623)
It seems that the generated results do not correspond well with the prompt. Could you help me solve this issue or explain why this might be happening？
2. face-id
ae-2334.jpg
![0000_0](https://github.com/KellyYutongHe/mpgd_pytorch/assets/42735246/3fa6f292-b9f4-4dd9-aede-81610d00271b)
wo-294.jpg
![0000_0](https://github.com/KellyYutongHe/mpgd_pytorch/assets/42735246/0d6e591d-5605-4e41-9f41-70b5efeb5a7d)
z-id10.png
![0000_0](https://github.com/KellyYutongHe/mpgd_pytorch/assets/42735246/c2f3e85f-8572-4df3-9956-289537012db0)
Why do the faces(people) generated by Face ID always wearing glasses and have the same background? Could you explain this to me?

I would greatly appreciate it if you could clarify my doubts. Many thanks!

**Comment by KellyYutongHe** [comment]
Hi! Thank you for using our code!
For your first question, we actually have already included a detailed discussion in our paper’s appendix (Section E.3). Long story short, when you are trying to generate something that is more out of distribution or harder, you should use more optimization steps (I.e. more —repeat steps).
For your second question, I suspect it is because the unconditional DDIM sample has glasses on. Since our model operates on the tangent space of this particular sample, and wearing glasses doesn’t change the identity of the person, you ended up getting photos of people wearing glasses all the time with the same random seed. Changing the seed can potentially solve this problem.
Hope this answer is helpful and please let me know if there is anything else I can help with.
